apiVersion: apps/v1
kind: Deployment
metadata:
  name: multivac-agents-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multivac-agents
  template:
    metadata:
      labels:
        app: multivac-agents
    spec:
      containers:
        - name: multivac-agents
          image: mvacstudio/multivac-agents:latest
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 8080
          env:
            - name: AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secret-auth0
                  key: auth0-client-id
            - name: AUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-auth0
                  key: auth0-client-secret
            - name: AUTH_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: secret-auth0
                  key: auth0-domain
            - name: GROQ_API_KEY
              valueFrom:
                  secretKeyRef:
                    name: secret-groq
                    key: groq-api-key
            - name: FIREWORKS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-fireworks-ai
                  key: fireworks-api-key
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-anthropic
                  key: apiKey