package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"multivac.network/services/agents/graph/model"
)

// FindAgentByID is the resolver for the findAgentByID field.
func (r *entityResolver) FindAgentByID(ctx context.Context, id string) (*model.Agent, error) {
	panic(fmt.Errorf("not implemented: FindAgentByID - findAgentByID"))
}

// FindGroupByID is the resolver for the findGroupByID field finds agents by groupId.
func (r *entityResolver) FindGroupByID(ctx context.Context, id string) (*model.Group, error) {
	panic(fmt.Errorf("not implemented: FindGroupByID - findGroupByID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
