// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Agent struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Key         string `json:"key"`
	Prompt      string `json:"prompt"`
	Engine      string `json:"engine"`
}

func (Agent) IsEntity() {}

type Engine struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Model       string `json:"model"`
}

type Group struct {
	ID     string   `json:"id"`
	Agents []*Agent `json:"agents,omitempty"`
}

func (Group) IsEntity() {}

type Mutation struct {
}

type NewAgent struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Engine      string `json:"engine"`
	Prompt      string `json:"prompt"`
}

type Query struct {
}
