name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mvacstudio/multivac-agents:$(date +%s) --tag mvacstudio/multivac-agents:latest
    - name: Push the Docker Image
      run: docker push mvacstudio/multivac-agents
