name: Notify in Progress

on:
  workflow_run:
    workflows:
      - "Build and Deploy to Linode CDN"
    types:
      - in_progress
jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: ">>> [${{ github.repository }}]\n:earth_americas:  **deployment in progress**"

