name: Notify Deployment Complete

on:
  workflow_run:
    workflows:
      - "Build and Deploy to Linode CDN"
    types:
      - completed
jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: ">>> [${{ github.repository }}]\n:white_check_mark:  **deployment complete**"
